[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://127.0.0.1:8545"
robinhood = "${RH_RPC_URL}"
robinhood_testnet = "${RH_TESTNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
robinhood = { key = "${BLOCKSCOUT_API_KEY}", url = "https://robinhoodchain.blockscout.com/api" }
